### PR TITLE
Implement new features.

### PR DESCRIPTION
**Pull request by ghost**
Here is a list of all the tasks I have completed.
- [X] Complete the rest of the algorithms.
- [X] Format most, if not all, of the files found in the algorithm and data structure folders.
- [X] Create a language folder for translators to implement new README files like README.en.md

The list of things that I have not done and that I hoped to complete.
- [ ] Comments on algorithm files to help beginners better understand what is happening.
- [ ] An English translation of the README.md file that would be placed in lang/README.en.md. Unfortunately; I haven't been able to get to this because the file is too big for me.

### CODE REVIEW

**Comment by tomieiro** [comment]
> Tenga en cuenta que hablo inglés y he traducido esta solicitud de extracción para facilitar el acceso.
> 
> Aquí hay una lista de todas las tareas que he completado.
> 
>     * [x]  Completa el resto de los algoritmos.
> 
>     * [x]  Formatee la mayoría, si no todos, los archivos que se encuentran en las carpetas de estructuras de datos y algoritmos.
> 
>     * [x]  Cree una carpeta de idioma para que los traductores implementen nuevos archivos README como README.en.md
> 
> 
> La lista de cosas que no he hecho y que esperaba completar.
> 
>     * [ ]  Comentarios sobre archivos de algoritmos para ayudar a los principiantes a comprender mejor lo que está sucediendo.
> 
>     * [ ]  Una traducción al inglés del archivo README.md que se colocaría en lang/README.en.md. Desafortunadamente; No he podido llegar a esto porque el archivo es demasiado grande para mí.

Oh, i'm really bad in spanish :sweat_smile: , but i got it.
But, it's ok to comment in english; in the future, repository will be documented both in portuguese and english!

**Comment by ghost** [comment]
Okay, awesome.

I'll be sure to speak my native English next time 😂.

**Comment by tomieiro** [comment]
> Okay, awesome.
> 
> I'll be sure to speak my native English next time joy.

Sure! Feel free to do that!

**Review by tomieiro — CHANGES_REQUESTED** [review]
On project specification, we adopted the C/C++/Java like format, which holds a semicolon on line ending. It's a good code style - how described by R. Ierusalimschy in Programming in Lua 3rd edition; it was defined on beginning of project. So, I'm so sorry, but all modification removing semicolon cannot be approved :cry: . 
But all files that you created, like Dijkstra's algorithm, you can leave on that way, without semicolon ending a line; on repo review, the maintainers can fix that :+1: .

**Comment by ghost** [comment]
Working on the changes you requested.

**Comment by ghost** [comment]
I've decided to close this and work on a library of my own. I find it better for what I had hoped to see in this repository. I have included you and others in the contributions list but my repository is completed revamped and does not include any code provided from the contributors in this repository.

Think of it as an english translation with an entirely new approach. Don't be a stranger though, I'd appreciate if you'd [check it out](https://github.com/shawnjb/lua-standard-library).

**Comment by tomieiro** [comment]
> I've decided to close this and work on a library of my own. I find it better for what I had hoped to see in this repository. I have included you and others in the contributions list but my repository is completed revamped and does not include any code provided from the contributors in this repository.
> 
> Think of it as an english translation with an entirely new approach. Don't be a stranger though, I'd appreciate if you'd [check it out](https://github.com/shawnjb/lua-standard-library).

Oh, that's nice! Thanks for sharing. I hope that you achieve your goal! 
Of course I will check this out later. Thanks!

**Pull request closed without merging**
